"""Pre-extracted triples for demo mode (US EV dataset sample)."""

DEMO_TRIPLES = [
    ("United States", "EV_MARKET_SHARE_2020", "2.4%"),
    ("Tesla", "MARKET_LEADER", "United States EV market"),
    ("Tesla", "MARKET_SHARE", "more than half"),
    ("General Motors", "ICE_PHASE_OUT_TARGET", "2035"),
    ("BloombergNEF", "PUBLISHES", "Electric Vehicle Outlook"),
    ("Colin McKerracher", "LEAD_AUTHOR_OF", "Electric Vehicle Outlook"),
    ("EVs", "DISPLACE_OIL", "1.7 million barrels per day"),
    ("China", "DOMINATES", "global EV market"),
    ("China", "MANUFACTURES", "battery cells"),
    ("Biden administration", "CHARGER_TARGET", "500000"),
    ("Biden administration", "CHARGER_TARGET_YEAR", "2030"),
    ("J.D. Power", "SURVEY_RESULT", "29.2%"),
    ("Elizabeth Krear", "WORKS_AT", "J.D. Power"),
    ("Federal government", "EV_TAX_CREDIT", "$7500"),
    ("ICCT", "PUBLISHED", "Evaluating electric vehicle market growth across U.S. cities"),
    ("ICCT", "PUBLISHED_IN", "September 2021"),
    ("ZEV states", "COMBINED_EV_SHARE", "5%"),
    ("Top 10 metro areas", "PUBLIC_CHARGERS_PER_MILLION", "935"),
    ("US EV sales H1 2023", "GROWTH_RATE", "51%"),
    ("BNEF", "OIL_DEMAND_PEAK", "2027"),
    ("UAW", "STRIKE_AGAINST", "GM"),
    ("UAW", "STRIKE_AGAINST", "Ford"),
    ("UAW", "STRIKE_AGAINST", "Stellantis"),
    ("Ford", "DELAYED", "EV investment"),
    ("Public charging", "FAILURE_RATE", "one in five"),
    ("Charging infrastructure market", "SIZE_2050", "$242 billion"),
    ("J.D. Power", "PROJECTS_MARKET_SCOPE_2026", "75%"),
    ("United States", "ANNUAL_EV_SALES_2018_2020", "315000"),
]
